SCREEN = (1000,500)
SCREEN_WIDTH = SCREEN[0]
SCREEN_HEIGHT = SCREEN[1]

FPS = 30

GAME_DIFFICULTY = 0
GAME_TITLE = ""

DEFAULT_FONT = "1001font deathstar"

GAME_SCREEN_MUSIC = ""
GAME_SCREEN_BACKGROUND = ""

GAMEPLAY_MUSIC = ""
GAMEPLAY_BACKGROUND = ""

PLAYER_ONE_SPRITE = ""
PLAYER_TWO_SPRITE = ""
TRAIL_SPRITE = ""

